### ISSUE TITLE
Make the shop + dropdown item in navigation hard coded

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-boxie#17]
Currently, the shop menu, which has a drop-down list of categories is hard coded.

Let's make the Shop link and drop-down in the menu hard coded, so that the drop-down category navigation can be dynamic. This is similar to how the Zest theme handles it.

**Comment by rudy-sasquatchstudio** [comment]
Updated.  Should be available in my pull request
